# Generated by Django 2.1.7 on 2019-02-23 08:43

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('population', models.IntegerField(default=0)),
                ('towns', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('date_mod', models.DateField()),
            ],
        ),
    ]
